# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official Node.js LTS Alpine image
FROM node:lts-alpine AS builder

# set working directory
WORKDIR /usr/src/app

# copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# copy source and build
COPY tsconfig.json .
COPY src ./src
RUN npm run build

# runtime image
FROM node:lts-alpine AS runtime
WORKDIR /usr/src/app

# copy built files and dependencies
COPY --from=builder /usr/src/app/build ./build
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY package.json .

# expose no port since stdio

# default command
CMD ["node","build/index.js"]
